# Generated by Django 4.1.5 on 2023-01-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
