# Generated by Django 4.1.5 on 2023-01-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_db', '0002_rename_firstname_user_name_remove_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='current_mutation',
            field=models.CharField(default='bd65600d-8669-4903-8a14-af88203add38', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(max_length=150),
        ),
    ]
